var tableauQuestion = [
    {   question : "Wenn Sie 80 km / h fahren und sich einem Wohngebiet nähern, müssen Sie:",
        propositionA : "Sie beschleunigen",
        propositionB : "Sie halten Ihre Geschwindigkeit, wenn Sie nicht an anderen Fahrzeugen vorbeifahren",
        propositionC : "Sie werden langsamer",
        propositionD : "Sie halten Ihre Geschwindigkeit",
        reponse : "C"},

    {   question : "Wenn Sie an einer Ampel rechts abbiegen, aber einen Fußgängerüberweg sehen, wie verhalten Sie sich?:",
        propositionA : "Sie lassen den Fußgänger passieren",
        propositionB : "Sie überprüfen, ob sich keine anderen verkehrsteilnehmer in der Nähe befinden",
        propositionC : "Sie warten, bis der Fußgänger überquert hat",
        propositionD : "Sie ignorieren den Fußgänger und fahren weiter",
        reponse : "C"},

    {   question : "Ohne vorherige Angabe ist die Geschwindigkeit in einem Wohngebiet: __ kmh",
        propositionA : "30",
        propositionB : "35",
        propositionC : "40",
        propositionD : "50",
        reponse : "A"},

  {   question : "Vor jedem Spurwechsel müssen Sie:",
        propositionA : "Seiten Spiegel überprüfen",
        propositionB : "toten Winkel überprüfen",
        propositionC : "Sie Signalisieren Ihre Absichten",
        propositionD : "Alles das oben Genannte",
        reponse : "D"},

  {   question : "Wie lange dauert es im Allgemeinen, bis 1,0 Promille Alkohol im Blut abgebaut ist?",
        propositionA : "10 Stunden",
        propositionB : "5 Stunden",
        propositionC : "1 Stunde",
        propositionD : "12 Stunden",
        reponse : "C"},

  {   question : "Wann können Sie an einer Ampel weiterfahren??",
        propositionA : "Wenn es grün ist",
        propositionB : "Wenn sich niemand an der Kreuzung befindet",
        propositionC : "Wenn sie sich in einer schulzone befinden",
        propositionD : "Wenn es grün und / oder rot ist und Sie rechts abbiegen",
        reponse : "D"},

  {   question : "Ein Fußgänger hat kein Kreuzsignal, was machst du??",
        propositionA : "Du lässt sie passieren",
        propositionB : "Sie beobachten, bevor Sie fortfahren",
        propositionC : "Sie signalisieren das sie überqueren können",
        propositionD : "Sie fahren fort, weil Ihre Ampel grün ist",
        reponse : "D"},

  {   question : "Was ist erlaubt, wenn Sie an einem anderen Fahrzeug vorbeifahren?",
        propositionA : "Sie folgen ihm genau, um schneller zu überholen",
        propositionB : "Sie überholen es, ohne die Fahrbahn zu verlassen",
        propositionC : "Sie fahren auf der gegenüberliegenden Straßenseite vorbei",
        propositionD : "Sie überschreiten das Tempolimit, um zu überholen",
        reponse : "C"},

  {   question : "Sie fahren auf einer Autobahn, die eine Höchstgeschwindigkeit von 120 km / h anzeigt. Der meiste Verkehr fährt mit 125 km / h, daher sollten Sie nicht schneller fahren als:",
        propositionA : "50 kmh",
        propositionB : "25 kmh",
        propositionC : "30 kmh",
        propositionD : "120 kmh",
        reponse : "D"},

  {   question : "Wenn Sie von einem anderen Fahrzeug überholt werden, ist es wichtig, dies NICHT zu tun:",
        propositionA : "aus bremsen",
        propositionB : "Die Spiegel überprüfen",
        propositionC : "Andere Verkehrsteilnehmer beobachten",
        propositionD : "Die Geschwindigkeit zu erhöhen",
        reponse : "D"},
]
